### ISSUE TITLE
Error running the testRandomAgent.py No module named 'PIL'

### ISSUE THREAD

**Issue by Kuldr** [rubenrtorrado/GVGAI_GYM#11]
When running the random agent test code provided it throws a long error that ends with the following.
`ModuleNotFoundError: No module named 'PIL'`

After some googling I found this Stackover flow post https://stackoverflow.com/questions/8863917/importerror-no-module-named-pil and following its advice of installing the package pillow everything worked.

I am not sure why the installation process given doesn't get this required package.

**Comment by pbontrager** [comment]
We must have missed this requirement since it is commonly included with a lot of setups. It has been added to the setup.py file now.
