### ISSUE TITLE
Error when trying to instantiate environment.

### ISSUE THREAD

**Issue by ivanfeliciano** [rubenrtorrado/GVGAI_GYM#13]
Hello, I get the next error when I try to run an instance of the environment (`env = gym.make("gvgai-aliens-lvl0-v0")`)

```$
Connecting to host 127.0.0.1 at port 52923 ...
Client connected to server [OK]
ERROR:root:module 'scipy.misc' has no attribute 'imread'
Traceback (most recent call last):
  File "/path_to_GVGAI_GYM/GVGAI_GYM/gym_gvgai/envs/gvgai/clients/GVGAI-PythonClient/src/utils/ClientCommGYM.py", line 305, in processLine
    self.sso.image = misc.imread(os.path.join(self.tempDir.name, 'gameStateByBytes.png'))
AttributeError: module 'scipy.misc' has no attribute 'imread'
```

I have `Pillow` installed. I'm running Python 3.7.3 and Ubuntu 18.04.

What can I do?

**Comment by pbontrager** [comment]
The new version of Scipy doesn't support imread anymore as they want you to just use Pillow of that. In the Ascii branch we have implemented the change but we have not pushed it to the main branch yet. If you are just working with the library you can change branches for now or you can use an older version of Scipy until we have a chance to merge a number of changes.
