### ISSUE TITLE
Adding level to game

### ISSUE THREAD

**Issue by aymericcousaert** [rubenrtorrado/GVGAI_GYM#14]
I'm using your repo and for testing issues I would like to add a level to the Zelda game. I added the new level .txt file, but the id is still not recognized in my project. I have tried to execute build.py, setup.py and gvgai_env.py and reinstall the package but none of these worked. What should I do ?

Thank you

**Comment by pbontrager** [comment]
Look at the set_level function inside env. You can provide a new level as a path and it will load it. For built in levels it only expects levels to range from 1 to 5.
